### ISSUE TITLE
Is the source code not commit?

### ISSUE THREAD

**Issue by gdcrx** [zspitz/Periscope.Debuggee#1]
In Periscope.Debuggee/VisualizerObjectSourceBase.cs file, the abstract method is "GetResponse", in ExpressionTreeVisualizer/Debuggee/VisualizerDataObjectSource.cs file,  the override method is "GenerateResponse", Which version of  Periscope.Debuggee is correct？

**Comment by zspitz** [comment]
ExpressionTreeVisualizer was not using the latest commit to Periscope.Debuggee. I've pulled the latest Periscope.Debuggee into ExpressionTreeVisualizer, modified VisualizerDataObjectSource.cs appropriately, and committed.

**Comment by zspitz** [comment]
If this issue is resolved, please close it.

I will do so in any case if nothing has been added to this issue in a week.

**Comment by gdcrx** [comment]
Ok,thanks a lot.
